import React from 'react';import { useEffect, useState } from 'react';
import { api } from '../api/client';
import StatusBadge from './StatusBadge';

function Field({f,value,onChange}){
  if(f.type==='select') return <label>{f.label}<select required={f.required} value={value ?? ''} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{(f.options||[]).map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></label>;
  return <label>{f.label}<input required={f.required} type={f.type||'text'} value={value ?? ''} onChange={e=>onChange(f.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/></label>;
}
export default function CrudPage({title,endpoint,columns,createFields=[],editFields=createFields,transformCreate,transformUpdate,actions=[]}){
 const[data,setData]=useState([]),[loading,setLoading]=useState(true),[form,setForm]=useState({}),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[open,setOpen]=useState(false);
 const load=()=>{setLoading(true);setError('');api.get(endpoint,{params:{search,limit:50}}).then(r=>setData(r.data||[])).catch(e=>setError(e.message||'Unable to load data')).finally(()=>setLoading(false));};
 useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[search]);
 const close=()=>{setEditing(null);setForm({});setOpen(false);setError('')};
 const save=async e=>{e.preventDefault();setSaving(true);setError('');try{const body=editing?(transformUpdate?transformUpdate(form):form):(transformCreate?transformCreate(form):form);if(editing)await api.put(`${endpoint}/${editing._id}`,body);else await api.post(endpoint,body);close();load()}catch(x){setError(x.message||'Unable to save record')}finally{setSaving(false)}};
 const del=async id=>{if(!confirm('Delete this record?'))return;try{await api.delete(`${endpoint}/${id}`);load()}catch(x){setError(x.message||'Unable to delete record')}};
 const run=async(a,row)=>{try{await a.run(row,load)}catch(x){setError(x.message||'Action failed')}};
 return <><div className="pagehead"><div><h1>{title}</h1><p>Manage {title.toLowerCase()} with server-side authorization.</p></div><button className="primary" onClick={()=>{setForm({});setEditing(null);setOpen(true)}}>+ Add {title.replace(/s$/,'')}</button></div><div className="toolbar"><input placeholder={`Search ${title.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)}/></div>{error&&<div className="error page-error">{error}</div>}<div className="card tablewrap">{loading?<div className="loading">Loading…</div>:<table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}<th>Actions</th></tr></thead><tbody>{data.length?data.map(x=><tr key={x._id}>{columns.map(c=><td key={c.key}>{c.key==='status'?<StatusBadge>{x[c.key]}</StatusBadge>:c.render?c.render(x):c.key.includes('.')?x[c.key.split('.')[0]]?.[c.key.split('.')[1]]||'—':x[c.key]??'—'}</td>)}<td className="actions"><button className="link" onClick={()=>{setEditing(x);setForm({...x});setOpen(true)}}>Edit</button><button className="link danger" onClick={()=>del(x._id)}>Delete</button>{actions.map((a,i)=><button key={i} className="link" onClick={()=>run(a,x)}>{a.label}</button>)}</td></tr>):<tr><td colSpan={columns.length+1} className="empty">No records found.</td></tr>}</tbody></table>}</div>{open&&<div className="modal"><form className="modalbox" onSubmit={save}><div className="cardhead"><h2>{editing?'Edit':'Add'} {title.replace(/s$/,'')}</h2><button type="button" onClick={close}>×</button></div>{(editing?editFields:createFields).map(f=><Field key={f.key} f={f} value={form[f.key]} onChange={v=>setForm(s=>({...s,[f.key]:v}))}/>)}{error&&<div className="error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Create'}</button></form></div>}</>;
}
